name: call-private-workflow

on:
  workflow_dispatch:

env:
   GITHUB_SERVER_URL: ${{ secrets.CI_DOMAIN_HTTPS_URL }}

jobs:

  stage-private-workflow:
    name: call-private-workflow
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "devops/test-gha"
          ref: 'main'
          token: ${{ secrets.CI_DOMAIN_TOKEN }}
          path: 'devops-test-gha'
          github-server-url: ${{ env.GITHUB_SERVER_URL }}

      - name: stage-workflows
        run: |
          ls -lrt devops-test-gha/.github/workflows
          cp devops-test-gha/.github/workflows/test-docker-runner.yml .github/workflows
          ls -lrt .github/workflows

  call-local-workflow:
    needs: stage-private-workflow
    uses: devops-test-gha/.github/workflows/test-docker-runner.yml@main
