name: call-private-workflow

on:
  workflow_dispatch:

jobs:

  call-private-workflow:
    name: call-private-workflow
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          repository: devops/test-gha
          token: ${{ secrets.CI_DOMAIN_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: devops-test-gha
        env:
          GITHUB_SERVER_URL: ${{ secrets.CI_DOMAIN_HTTPS_URL }}

    
