name: call-private-workflow

on:
  workflow_dispatch:

jobs:
  stage-private-workflow:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
        with:
          repository: actions-int/hello-world-action
          token: ${{ secrets.CI_DOMAIN_TOKEN}}
          path: hello-world-action
          github-server-url: ${{ secrets.GITHUB_SERVER_URL }}
      - name: Run reusable workflow
        uses: ./hello-world-action/hello-world
        with:
          who-to-greet: 'Lets get some testing action going...'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

