name: call-private-workflow

on:
  workflow_dispatch:

env:
   GITHUB_SERVER_URL: ${{ secrets.CI_DOMAIN_HTTPS_URL }}

jobs:

  call-private-workflow:
    name: call-private-workflow
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "devops/test-gha"
          ref: 'main'
          token: ${{ secrets.CI_DOMAIN_TOKEN }}
          path: 'devops-test-gha'
          github-server-url: ${{ env.GITHUB_SERVER_URL }}

      - name: get-workspace-details
        run: |
          pwd
          ls -lrt devops-test-gha
          ls -lrt devops-test-gha/.github/workflows

      - name: run-test-action
        uses: devops-test-gha/.github/workflows/test-docker-runner.yaml@main
